coe/app/urls.py
#imports django
from django.urls import path
from django.conf.urls import url
#Import de modulos personales
from . import views as views
from . import app_apis as app_apis
from . import autocomplete


#Definimos paths de la app
app_name = 'app'
urlpatterns = [
    #App
    path('config', app_apis.AppConfig, name='AppConfig'),
    path('registro', app_apis.registro, name='registro'),
    path('foto_perfil', app_apis.foto_perfil, name='foto_perfil'),
    path('encuesta', app_apis.encuesta, name='encuesta'),
    path('start/tracking', app_apis.start_tracking, name='start_tracking'),
    path('tracking', app_apis.tracking, name='tracking'),
    path('salvoconducto', app_apis.pedir_salvoconducto, name='pedir_salvoconducto'),
    path('get/salvoconducto', app_apis.ver_salvoconducto, name='ver_salvoconducto'),
    path('control/salvoconducto', app_apis.control_salvoconducto, name='control_salvoconducto'),
    path('denuncia', app_apis.denuncia_anonima, name='denuncia_anonima'),
    path('get/notificacion', app_apis.notificacion, name='notificacion'),
    #Testing
    path('send/notificacion', views.enviar_notificacion, name='enviar_notificacion'),
    path('save/notificacion', views.guardar_notificacion, name='enviar_notificacion'),
    #Descarga
    path('coe_app', views.download_app, name='download_app'),
    #path('simmov_app', views.download_control, name='download_control'),
    #Autocomplete:
    url(r'^appdata-autocomplete/$', autocomplete.AppDataAutocomplete.as_view(), name='appdata-autocomplete'),
    url(r'^dispositivo-autocomplete/$', autocomplete.DispositivoAutocomplete.as_view(), name='dispositivo-autocomplete'),
]

coe/coe/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path, include

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from django.conf import settings
#Imports Extras
import debug_toolbar

#Path
urlpatterns = [
    path('admin/', admin.site.urls),
    #Admin-User Paths
    url(r'^login/$', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),
    #Apps:
    path('', include('core.urls')),
    path('consultas/', include('consultas.urls')),
    path('georef/', include('georef.urls')),
    path('noticias/', include('noticias.urls')),
    path('operadores/', include('operadores.urls')),
    path('actas/', include('actas.urls')),
    path('tareas/', include('tareas.urls')),
    path('inventario/', include('inventario.urls')),
    path('informacion/', include('informacion.urls')),
    path('seguimiento/', include('seguimiento.urls')),
    path('geotracking/', include('geotracking.urls')),
    path('permisos/', include('permisos.urls')),
    path('graficos/', include('graficos.urls')),
    path('documentos/', include('documentos.urls')),
    path('inscripciones/', include('inscripciones.urls')),
    path('background/', include('background.urls')),
    path('tablero/', include('tablero.urls')),
    #APIS:
    path('api_refs/', include('wservices.urls')),
    path('ide/', include('geotracking.ide_urls')),
    path('covid19/', include('app.urls')),
    #Manejo de Archivos Privados:
    #path('archivos/', include('operadores.file_urls')),#Lo hacemos desde ahi por que depende de permisos
]
#Agregamos destinos de Archivos Estaticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coe/graficos/urls.py
#imports django
from django.conf.urls import url
from django.urls import path
#Import de modulos personales
from . import views

#Definimos paths de la app
app_name = 'graficos'
urlpatterns = [
    #Administrador
    path('', views.menu, name='menu'),
    #Listados
    path('lista', views.lista_graficos, name='lista_graficos'),
    path('lista/tipo/<str:tipo_id>', views.lista_graficos, name='lista_tipo'),
    path('ver/<int:grafico_id>', views.ver_grafico, name='ver_grafico'),
    #ABM GRAFICO
    path('crear', views.crear_grafico, name='crear_grafico'),
    path('mod/<int:grafico_id>', views.crear_grafico, name='mod_grafico'),
    path('reset/<int:grafico_id>', views.reniciar_datos, name='reniciar_datos'),
    path('cambiar/estado/<int:grafico_id>', views.cambiar_estado, name='cambiar_estado'),
    path('eliminar/<int:grafico_id>', views.eliminar_grafico, name='eliminar_grafico'),
    #ABM DATOS
    path('crear/columna/<int:grafico_id>', views.crear_columna, name='crear_columna'),
    path('mod/columna/<int:grafico_id>/<int:columna_id>', views.crear_columna, name='mod_columna'),
    
    path('agregar/fila/<int:grafico_id>', views.agregar_fila, name='agregar_fila'),
    path('mod/dato/<int:dato_id>', views.mod_dato, name='mod_dato'),

]

coe/graficos/models.py
#Import Django
from django.db import models
from django.core.cache import cache
#Imports de la app
from .choices import TIPO_GRAFICO

# Create your models here.
class Grafico(models.Model):
    nombre = models.CharField('Nombre Informatico', max_length=100)
    verbose_name = models.CharField('Nombre Para Mostrar', max_length=100)
    tipo = models.CharField('Tipo Grafico', choices=TIPO_GRAFICO, max_length=2, default='L')
    update = models.DateField('Ultimo Dato Cargado', null=True)
    cant_datos = models.IntegerField('Cantidad de Datos a Mostrar', default=15)
    publico = models.BooleanField(default=False)
    def __str__(self):
        return self.nombre + ': ' + str(self.update)
    def agregar_dato(self, update_date, columna_nombre, fila, valor):
        #Buscamos/Creamos la columna
        try:
            columna = [c for c in self.columnas.all() if c.nombre == columna_nombre][0]
        except:
            cant = self.columnas.count() + 1
            columna = Columna(grafico=self, orden=cant, nombre=columna_nombre)
            columna.save()
        #Eliminamos si habia un dato en esa "celda"
        columna.datos.filter(fila=fila).delete()
        #Agregamos el dato:
        dato = Dato()
        dato.grafico = self
        dato.columna = columna
        dato.fila = fila
        dato.valor = valor
        dato.save()
        #Informamos que fue Actualizado
        self.update = update_date
        self.save()
    def reiniciar_datos(self):
        cache.set(self.nombre, [])
        Dato.objects.filter(columna__grafico=self).delete()
    def bulk_dato(self, update_date, columna_nombre, fila, valor):
        #Buscamos/Creamos la columna
        try:
            columna = [c for c in self.columnas.all() if c.nombre == columna_nombre][0]
        except:
            cant = self.columnas.count() + 1
            columna = Columna(grafico=self, orden=cant, nombre=columna_nombre)
            columna.save()
        #Agregamos el dato:
        dato = Dato()
        dato.grafico = self
        dato.columna = columna
        dato.fila = fila
        dato.valor = valor
        #Lo mandamos a la cache
        datos = cache.get(self.nombre)
        datos.append(dato)
        cache.set(self.nombre, datos)
    def bulk_save(self):
        datos = cache.get(self.nombre)
        self.reiniciar_datos()
        Dato.objects.bulk_create(datos)
    def cabecera(self):
        #Obtenemos todo lo necesario para procesar
        return ['Fecha'] + [c.nombre for c in self.columnas.all() if c.mostrar == True]
    def obtener_datos(self):
        #Para graficos de Lineas
        if self.tipo in ('L', 'C'):
            #Traemos todo el bloque de datos ya indexado
            dict_datos = {}
            for columna in self.columnas.all():
                if columna.mostrar:
                    for dato in columna.datos.all():
                        dict_datos[dato.columna.nombre,dato.fila] = dato
            #Referencias disponibles
            if self.columnas.all():#Si tiene columnas
                filas = [d.fila for d in  self.columnas.first().datos.all()]
                #Creamos nuestro vector
                datos = []
                for fila in filas:#Por cada Fecha
                    #Generamos cada linea
                    dato = []
                    for columna in self.cabecera()[1:]:
                        try:
                            dato.append(dict_datos[columna,fila])
                        except KeyError:#Si faltan datos por columna vacia
                            new = Dato()#Lo creamos con valor 0
                            new.columna = self.columnas.get(nombre=columna)
                            new.fila = fila
                            new.valor = 0
                            new.save()
                            dato.append(new)
                    #Agregamos la linea
                    datos.append(dato)
                return datos[-int(self.cant_datos):]#Entregamos la cantidad esperada
        #Para Graficos de Torta
        elif self.tipo == 'P':
            datos = self.columnas.first().datos.all()#Solo es una columna
            datos = datos.order_by('-valor')
            return [d for d in  datos][:self.cant_datos]#De mayor a menor

class Columna(models.Model):
    grafico = models.ForeignKey(Grafico, on_delete=models.CASCADE, related_name="columnas")
    nombre = models.CharField('Nombre', max_length=50)
    orden = models.IntegerField('Orden')
    mostrar = models.BooleanField(default=True)
    class Meta:
        ordering = ['-mostrar', 'orden']
    def __str__(self):
        return self.nombre

class Dato(models.Model):
    columna = models.ForeignKey(Columna, on_delete=models.CASCADE, related_name="datos")
    fila = models.CharField('Fila', max_length=100, null=True)
    valor = models.DecimalField('Valor', max_digits=12, decimal_places=2)
    class Meta:
        ordering = ['pk', ]
    def __str__(self):
        return self.fila + '-' + self.columna.nombre + ' Cant: ' + str(self.valor) 

coe/graficos/forms.py
#Imports Python
from datetime import date
#Imports Django
from django import forms
#Imports extra

#Imports del proyecto

#Imports de la app
from .models import Grafico, Columna, Dato

#Definimos nuestros forms
class GraficoForm(forms.ModelForm):
    class Meta:
        model = Grafico
        fields= '__all__'
        exclude = ('publico', 'update')
    def __init__(self, *args, **kwargs):
        super(GraficoForm, self).__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['nombre'].widget.attrs['readonly'] = True

class ColumnaForm(forms.ModelForm):
    class Meta:
        model = Columna
        fields= '__all__'
        widgets = {
            'grafico': forms.TextInput(attrs={'readonly':'readonly'}),
        }
    def __init__(self, *args, **kwargs):
        super(ColumnaForm, self).__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['nombre'].widget.attrs['readonly'] = True

class DatoForm(forms.ModelForm):
    class Meta:
        model = Dato
        fields= '__all__'
        widgets = {
            'columna': forms.HiddenInput(),
        }

coe/graficos/views.py
#Imports de Django
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import permission_required
#Imports del Proyecto
try:
    from coe.credenciales import GEOPOSITION_GOOGLE_MAPS_API_KEY
except:
    GEOPOSITION_GOOGLE_MAPS_API_KEY = ''
#Imports de la app
from .models import Grafico, Columna, Dato
from .forms import GraficoForm, ColumnaForm, DatoForm

# Create your views here.
@permission_required('operadores.menu_graficos')
def menu(request):
    return render(request, 'menu_graficos.html', {})

@permission_required('operadores.menu_graficos')
def lista_graficos(request, tipo_id=None):
    graficos = Grafico.objects.all()
    #Filtramos si fue requerido
    if tipo_id:
        graficos = graficos.filter(tipo=tipo_id)
    #Entregamos lista
    return render(request, 'lista_graficos.html', {
        'graficos': graficos,
        'has_table': True,
    })

@permission_required('operadores.menu_graficos')
def ver_grafico(request, grafico_id, geoposiciones=None):
    grafico = Grafico.objects.get(pk=grafico_id)
    #Agregar logica para tipo de graficos segun tipo
    if grafico.tipo == 'L':
        subtemplate = 'lineas.html'
    elif grafico.tipo == 'P':
        subtemplate = 'torta.html'
    elif grafico.tipo == 'C':
        subtemplate = 'columnas.html'
    elif grafico.tipo == 'MP':
        subtemplate = 'mapa_puntos.html'
    return render(request, 'ver_grafico.html', {
        'grafico': grafico,
        'subtemplate': subtemplate,
        'geoposiciones': geoposiciones,
        'gmkey': GEOPOSITION_GOOGLE_MAPS_API_KEY,
    })

#administracion de graficos
@permission_required('operadores.menu_graficos')
def crear_grafico(request, grafico_id=None):
    grafico = None
    if grafico_id:
        grafico = Grafico.objects.get(pk=grafico_id)
    form = GraficoForm(instance=grafico)
    if request.method == "POST":
        form = GraficoForm(request.POST, instance=grafico)
        if form.is_valid():
            grafico = form.save()
            return redirect('graficos:ver_grafico', grafico_id=grafico.id)
    return render(request, "extras/generic_form.html", {'titulo': "Crear/Modificar Grafico", 'form': form, 'boton': "Confirmar", })

@permission_required('operadores.menu_graficos')
def reniciar_datos(request, grafico_id):
    grafico = Grafico.objects.get(pk=grafico_id)
    #Elegimos datos para eliminar
    filas = [d.fila for d in  grafico.columnas.first().datos.all()]
    filas = filas[-grafico.cant_datos:]
    #Eliminamos todos esos datos
    Dato.objects.filter(fila__in=filas).delete()
    #Quitamos su ultima actualizacion
    grafico.update = None
    grafico.save()
    return redirect('graficos:lista_graficos')

@permission_required('operadores.menu_graficos')
def cambiar_estado(request, grafico_id):
    grafico = Grafico.objects.get(pk=grafico_id)
    grafico.publico = not grafico.publico
    grafico.save()
    return redirect('graficos:ver_grafico', grafico_id=grafico.id)

@permission_required('operadores.menu_graficos')
def eliminar_grafico(request, grafico_id):
    grafico = Grafico.objects.get(pk=grafico_id)
    grafico.delete()
    return redirect('graficos:lista_graficos') 

@permission_required('operadores.menu_graficos')
def crear_columna(request, grafico_id, columna_id=None):
    grafico = Grafico.objects.get(pk=grafico_id)
    columna = None
    if columna_id:
        columna = Columna.objects.get(pk=columna_id)
    form = ColumnaForm(instance=columna,
        initial={
            'grafico': grafico,
        })
    if request.method == "POST":
        form = ColumnaForm(request.POST, instance=columna)
        if form.is_valid():
            columna = form.save(commit=False)
            columna.grafico = grafico
            columna.save()
            return redirect('graficos:ver_grafico', grafico_id=grafico.id)
    return render(request, "extras/generic_form.html", {'titulo': "Crear/Modificar Dato", 'form': form, 'boton': "Confirmar", })

@permission_required('operadores.menu_graficos')
def agregar_fila(request, grafico_id):
    grafico = Grafico.objects.get(pk=grafico_id)
    if request.method == 'POST':
        for columna in grafico.columnas.all():
            dato = Dato()
            dato.columna = columna
            dato.fila = request.POST['nombre']
            dato.valor = request.POST[str(columna.id)]
            dato.save()
        return redirect('graficos:ver_grafico', grafico_id=grafico.id)
    return render(request, "agregar_fila.html", {
        'grafico': grafico, 
        'has_form': True,
    })

@permission_required('operadores.menu_graficos')
def mod_dato(request, dato_id):
    dato = Dato.objects.get(pk=dato_id)
    form = DatoForm(instance=dato)
    if request.method == "POST":
        form = DatoForm(request.POST, instance=dato)
        if form.is_valid():
            form.save()
            return redirect('graficos:ver_grafico', grafico_id=dato.columna.grafico.id)
    return render(request, "extras/generic_form.html", {'titulo': "Crear/Modificar Dato", 'form': form, 'boton': "Confirmar", })

coe/graficos/templates/agregar_fila.html
{% extends 'base_informacion.html' %}

{% load seguridad_tags%}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="formulario_custom col-sm-8">
                <h2>Agregar Fila de Datos a {{grafico.nombre}}</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Mostramos errores -->
                    {% for field in form %}
					    {% if field.errors %}
                            <li>
                                {{ field.label }}: {{ field.errors|striptags }}
                            </li>
                        {% endif %}
				    {% endfor %}
                    <!-- Formulario -->
                    <div class="grupo">
                        <p class="campo">
                            <label>Nombre Fila</label>
                            <input type="text" id="nombre" name="nombre">
                        </p>
                        {% for columna in grafico.columnas.all %}
                            <p class="campo">
                                <label>
                                    {{columna.nombre}}
                                </label>
                                <input id="{{columna.id}}" name="{{columna.id}}" type="number" value=0 />
                            </p>
                        {% endfor %}
                        <button type="submit">Cargar Linea</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

coe/graficos/templates/base_graficos.html
{% extends 'base/base.html' %}

{% load static %}
{% block custom_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/graficos.css' %}" />
{% endblock %}

{% block content %}

{% endblock %}

{% block custom_script %}
    
{% endblock %}

coe/graficos/templates/columnas.html
{% block content %}
    <a href="{% url 'graficos:ver_grafico' grafico_id=graf_datos.id %}">
        <div id="chart-{{graf_datos.nombre}}" class="grafico"></div>
    </a>
{% endblock %}

{% load grafic_tags %}

{% block custom_script %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {'packages':['corechart']});
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = google.visualization.arrayToDataTable([
            
                {{graf_datos.cabecera|safe}}
                
                {% for linea in graf_datos.obtener_datos %}
                    {% ct_showlinea linea as linea_str %}
                    ,{{linea_str|safe}}
                {% endfor %}
            
            ]);

            var options = {
                title: '{{graf_datos.verbose_name}}',
                legend: { position: 'top', maxLines: 3 },
                bar: { groupWidth: '75%' },
                isStacked: true,
            };

            var chart = new google.visualization.ColumnChart(document.getElementById("chart-{{graf_datos.nombre}}"));
            chart.draw(data, options);
        }
    </script>
{% endblock %}      

coe/graficos/templates/lineas.html
{% block content %}
    <a href="{% url 'graficos:ver_grafico' grafico_id=graf_datos.id %}">
        <div id="chart-{{graf_datos.nombre}}" class="grafico"></div>
    </a>
{% endblock %}

{% load grafic_tags %}

{% block custom_script %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {'packages':['corechart']});
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                
                {{graf_datos.cabecera|safe}}
                
                {% for linea in graf_datos.obtener_datos %}
                    {% ct_showlinea linea as linea_str %}
                    ,{{linea_str|safe}}
                {% endfor %}

            ]);

            var options = {
                title: '{{graf_datos.verbose_name}}',
                curveType: 'function',
                legend: { position: 'bottom' 
            }
        };

            var chart = new google.visualization.LineChart(document.getElementById('chart-{{graf_datos.nombre}}'));
            chart.draw(data, options);
        }
    </script>


    <style>
        {% if graf_datos.alto %}
            .grafico {
                height: {{graf_datos.alto}}px;
            }
        {% endif %}
    </style>
{% endblock %}

coe/graficos/templates/lista_graficos.html
{% extends 'base_graficos.html' %}
{% load static %}
{% block content %}
    <div class="beneficiario container">
        <div class="row">
            <h2>Graficos</h2>
        </div>
        <div class="row">
        <div>
            <table class="listado table" id="table">
                <thead>
                    <tr>
                        <th>Tipo</th>
                        <th>Nombre</th>
                        <th>Publico</th>
                        <th>Ultima Actualizacion</th>
                        <th>Valores a Mostrar</th>
                        <th>Ver</th>
                    </tr>
                </thead>
                <tbody>
                    {% for grafico in graficos %}
                        <tr>
                            <td data-title="Tipo: ">
                                <a href="{% url 'graficos:lista_tipo' tipo_id=grafico.tipo %}">
                                    {{grafico.get_tipo_display}}
                                </a>
                            </td>
                            <td data-title="Nombre: ">{{grafico.verbose_name}}</td>
                            <td data-title="Publico: ">
                                {% if grafico.publico %}
                                    <img class="iconsx2" src="/static/img/icons/public.png" alt="Es Publico">
                                {% else %}
                                    <img class="iconsx2" src="/static/img/icons/private.png" alt="Es Privado">
                                {% endif %}
                            </td>
                            <td data-title="Ultima Actualizacion: ">{{grafico.update}}</td>
                            <td data-title="Valores a Mostrar: ">
                                {% for dato in grafico.cabecera%}
                                    {% if forloop.first %}
                                        <ul>
                                    {% endif %}
                                        <li>{{dato}}</li>
                                    {% if forloop.last %}
                                        </ul>
                                    {% endif %}
                                {% endfor %}
                            <td data-title="Ver: "><a href="{% url 'graficos:ver_grafico' grafico_id=grafico.id %}" target="_blank">(Detalle)</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

coe/graficos/templates/menu_graficos.html
{% extends 'base_graficos.html' %}

{% load seguridad_tags%}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Menu Graficos:</h1>
                    <div class="col-md-8">
                        <ul class="menu_botones">
                            <li><a href="{% url 'graficos:lista_graficos'  %}">Lista de Graficos</a></li>
                            <li><a href="{% url 'graficos:crear_grafico'  %}">Crear Grafico</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        {% include 'info_user.html' %}
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

coe/graficos/templates/torta.html
{% block content %}
    <a href="{% url 'graficos:ver_grafico' grafico_id=graf_datos.id %}">
        <div id="chart-{{graf_datos.nombre}}" class="grafico"></div>
    </a>
{% endblock %}

{% block custom_script %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
                {{graf_datos.cabecera|safe}}
                
                {% for dato in graf_datos.obtener_datos %}
                    ,['{{dato.fila}}', {{dato.valor|floatformat:"0" }}]
                {% endfor %}

            ]);

        var options = {
          title: '{{graf_datos.verbose_name}}',
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart-{{graf_datos.nombre}}'));
        chart.draw(data, options);
      }
    </script>
{% endblock %}

coe/graficos/templates/ver_grafico.html
{% extends 'base_graficos.html' %}

{% load static %}
{% load seguridad_tags%}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h2><b>{{grafico.verbose_name}}</b></h2>
                    <div class="col-md-8">
                        <hr>
                        <p><b>Ultima Actualizacion:</b> {{grafico.update}}</p>
                        <p><b>Tipo:</b> {{grafico.get_tipo_display}}</p>
                        <p><b>Es Publico:</b>
                            {% if grafico.publico %}
                                Publicado
                            {% else %}
                                Privado
                            {% endif %}
                        </p>
                        <p><b>Columnas a Mostrar:</b>
                            <ul>
                                {% for columna in grafico.columnas.all %}
                                    {% if columna.mostrar %}
                                        <li>{{columna.nombre}}</li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </p>
                        <hr>
                        {% include subtemplate with graf_datos=grafico %}
                    </div>
                    <div class="col-md-4">
                        <ul class="menu_botones">
                            {% if perms.operadores.admin_informacion %}
                                <li><a href="{% url 'graficos:mod_grafico' grafico_id=grafico.id %}">Editar Grafico</a></li>
                                {% if grafico.publico %}
                                    <li><a href="{% url 'graficos:cambiar_estado' grafico_id=grafico.id  %}">Hacer Privado</a></li>
                                {% else %}
                                    <li><a href="{% url 'graficos:cambiar_estado' grafico_id=grafico.id  %}">Hacer Publico</a></li>
                                {% endif %}
                                <hr>
                                <li><a href="{% url 'graficos:crear_columna' grafico_id=grafico.id  %}">Agregar Columna</a></li>
                                <li><a href="{% url 'graficos:agregar_fila' grafico_id=grafico.id  %}">Agregar Fila de Datos</a></li>
                                <li><a href="{% url 'graficos:reniciar_datos' grafico_id=grafico.id  %}">Reiniciar Datos</a></li>
                                <li><a href="{% url 'graficos:eliminar_grafico' grafico_id=grafico.id  %}">Eliminar</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="row">
                    {% for columna in grafico.columnas.all %}
                        <br>
                        <h4>
                            <b>Columna:</b> {{columna.nombre}}
                            {% if columna.mostrar %}
                                <img class="icons" src="/static/img/icons/public.png" alt="Es Publico">
                            {% else %}
                                <img class="icons" src="/static/img/icons/private.png" alt="Oculto">
                            {% endif %}
                            {% if perms.operadores.admin_informacion %}
                                <a href="{% url 'graficos:mod_columna' grafico_id=grafico.id columna_id=columna.id %}">
                                    <img class="icons" src="{% static '/img/icons/change.png' %}">
                                </a>
                            {% endif %}
                        </h4>
                        <div class="col-md-12">
                            <table class="listado">
                                <thead>
                                    <tr>
                                        <th>Fila</th>
                                        <th>Valor</th>
                                        <th>Modificar</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for dato in columna.datos.all %}
                                        <tr>
                                            <td>{{dato.fila}}</td>
                                            <td>{{dato.valor}}</td>
                                            <td>
                                                {% if perms.operadores.admin_informacion %}
                                                    <a href="{% url 'graficos:mod_dato' dato_id=dato.id %}">
                                                        <img class="icons" src="{% static '/img/icons/change.png' %}">
                                                    </a>
                                                {% else %}
                                                    No puede Editar
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <hr>
                    {% endfor %}
                </div>
            </div>
        </section>
    </section>
{% endblock %}