coe/app/urls.py
#imports django
from django.urls import path
from django.conf.urls import url
#Import de modulos personales
from . import views as views
from . import app_apis as app_apis
from . import autocomplete


#Definimos paths de la app
app_name = 'app'
urlpatterns = [
    #App
    path('config', app_apis.AppConfig, name='AppConfig'),
    path('registro', app_apis.registro, name='registro'),
    path('foto_perfil', app_apis.foto_perfil, name='foto_perfil'),
    path('encuesta', app_apis.encuesta, name='encuesta'),
    path('start/tracking', app_apis.start_tracking, name='start_tracking'),
    path('tracking', app_apis.tracking, name='tracking'),
    path('salvoconducto', app_apis.pedir_salvoconducto, name='pedir_salvoconducto'),
    path('get/salvoconducto', app_apis.ver_salvoconducto, name='ver_salvoconducto'),
    path('control/salvoconducto', app_apis.control_salvoconducto, name='control_salvoconducto'),
    path('denuncia', app_apis.denuncia_anonima, name='denuncia_anonima'),
    path('get/notificacion', app_apis.notificacion, name='notificacion'),
    #Testing
    path('send/notificacion', views.enviar_notificacion, name='enviar_notificacion'),
    path('save/notificacion', views.guardar_notificacion, name='enviar_notificacion'),
    #Descarga
    path('coe_app', views.download_app, name='download_app'),
    #path('simmov_app', views.download_control, name='download_control'),
    #Autocomplete:
    url(r'^appdata-autocomplete/$', autocomplete.AppDataAutocomplete.as_view(), name='appdata-autocomplete'),
    url(r'^dispositivo-autocomplete/$', autocomplete.DispositivoAutocomplete.as_view(), name='dispositivo-autocomplete'),
]

coe/coe/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path, include

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from django.conf import settings
#Imports Extras
import debug_toolbar

#Path
urlpatterns = [
    path('admin/', admin.site.urls),
    #Admin-User Paths
    url(r'^login/$', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),
    #Apps:
    path('', include('core.urls')),
    path('consultas/', include('consultas.urls')),
    path('georef/', include('georef.urls')),
    path('noticias/', include('noticias.urls')),
    path('operadores/', include('operadores.urls')),
    path('actas/', include('actas.urls')),
    path('tareas/', include('tareas.urls')),
    path('inventario/', include('inventario.urls')),
    path('informacion/', include('informacion.urls')),
    path('seguimiento/', include('seguimiento.urls')),
    path('geotracking/', include('geotracking.urls')),
    path('permisos/', include('permisos.urls')),
    path('graficos/', include('graficos.urls')),
    path('documentos/', include('documentos.urls')),
    path('inscripciones/', include('inscripciones.urls')),
    path('background/', include('background.urls')),
    path('tablero/', include('tablero.urls')),
    #APIS:
    path('api_refs/', include('wservices.urls')),
    path('ide/', include('geotracking.ide_urls')),
    path('covid19/', include('app.urls')),
    #Manejo de Archivos Privados:
    #path('archivos/', include('operadores.file_urls')),#Lo hacemos desde ahi por que depende de permisos
]
#Agregamos destinos de Archivos Estaticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coe/inscripciones/urls.py
#imports django
from django.urls import path
from django.conf.urls import url
#Import de modulos personales
from . import views

#Definimos paths de la app
app_name = 'inscripciones'
urlpatterns = [
    #Publico
    path('profesional/salud', views.inscripcion_salud, name='inscripcion_salud'),
    path('voluntario/social', views.inscripcion_social, name='inscripcion_social'),
    path('voluntario/social/explicacion', views.explicacion_voluntario_social, name='explicacion_voluntario_social'),
    path('proyecto/estudiantil', views.inscripcion_proyecto, name='inscripcion_proyecto'),
    path('foto/<int:inscripcion_id>', views.subir_foto, name='subir_foto'),
    path('frente_dni/<int:inscripcion_id>', views.cargar_frente_dni, name='cargar_frente_dni'),
    path('reverso_dni/<int:inscripcion_id>', views.cargar_reverso_dni, name='cargar_reverso_dni'),
    path('ver/<int:inscripcion_id>/<str:num_doc>', views.ver_inscripto, name='ver_inscripto'),
    path('ver/capacitacion/<int:inscripto_id>/<int:capacitacion_id>', views.ver_capacitacion, name='ver_capacitacion'),
    #Turnos
    path('turnero/editar/<int:ubicacion_id>', views.editar_turnos, name='editar_turnos'),
    url(r'turnero/bajar/(?P<ubicacion_id>[0-9]+)/(?P<fecha>\d{4}-\d{2}-\d{2})/(?P<hora>\d{2}:\d{2})/$', views.bajar_turno, name='bajar_turno'),
    path('turnero/<int:ubicacion_id>/<int:inscripto_id>/', views.turnero, name='turnero'),
    url(r'turnero/(?P<ubicacion_id>[0-9]+)/(?P<inscripto_id>[0-9]+)/(?P<fecha>\d{4}-\d{2}-\d{2})/(?P<hora>\d{2}:\d{2})/$', views.turnero, name='turno_seleccionado'),
    #Administracion
    path('', views.menu, name='menu'),
    path('lista/tareas', views.lista_tareas, name='lista_tareas'),
    path('lista/<str:tipo_inscripto>/', views.lista_voluntarios, name='lista_voluntarios'),
    path('lista/tarea/<str:tarea_id>/', views.lista_por_tarea, name='lista_por_tarea'),
    path('lista/proyectos', views.lista_proyectos, name='lista_proyectos'),
    path('avanzar/estado/<int:inscripcion_id>', views.avanzar_estado, name='avanzar_estado'),
    path('asignar/tarea/<int:inscripcion_id>', views.asignar_tarea, name='asignar_tarea'),
    path('inscripto/email/<int:inscripcion_id>', views.enviar_email, name='enviar_email'),
    #Proyecto
    path('proyecto/panel/<str:token>/', views.panel_proyecto, name='panel_proyecto'),
    path('proyecto/archivo/<str:token>/', views.cargar_archivo_proyecto, name='cargar_archivo_proyecto'),
    path('proyecto/aval/<str:token>/', views.cargar_aval_institucional, name='cargar_aval_institucional'),
    path('proyecto/responsable/<str:token>/', views.cargar_responsable_institucional, name='cargar_responsable_institucional'),
    path('proyecto/responsable/<str:token>/<int:individuo_id>', views.cargar_responsable_institucional, name='mod_responsable_institucional'),
    path('proyecto/cargar/tutor/<str:token>/<int:voluntario_id>', views.cargar_tutor, name='cargar_tutor'),
    path('proyecto/cargar/autorizacion/<str:token>/<int:voluntario_id>', views.cargar_autorizacion, name='cargar_autorizacion'),
    path('proyecto/voluntario/<str:token>/', views.cargar_voluntario, name='cargar_voluntario'),
    path('proyecto/mod/voluntario/<str:token>/<int:individuo_id>', views.cargar_voluntario, name='mod_voluntario_proyecto'),
    path('proyecto/del/voluntario/<str:token>/<int:individuo_id>', views.quitar_voluntario_proyecto, name='quitar_voluntario_proyecto'),
    #COCA
    path('coca', views.pedir_coca, name='pedir_coca'),   
    #COCA PERSONAL
    path('coca/persona/', views.peticion_persona, name='peticion_persona'),
    path('coca/persona/ver/<str:token>', views.ver_peticion_persona, name='ver_peticion_persona'),
    path('coca/persona/mod/<int:peticion_id>', views.peticion_persona, name='mod_peticion_persona'),
    path('coca/persona/finalizar/<int:peticion_id>', views.finalizar_peticion, name='finalizar_peticion'),
    path('coca/persona/del/<int:peticion_id>', views.eliminar_peticion, name='eliminar_peticion'),
    path('coca/persona/enviar_email/<int:peticion_id>', views.peticion_enviar_email, name='peticion_enviar_email'),
    path('coca/personas/lista', views.lista_peticiones_personales, name='lista_peticiones_personales'),
    path('coca/personas/lista/estado/<estado>', views.lista_peticiones_personales, name='lista_peticiones_personales'),
    path('coca/personas/aprobar/<int:peticion_id>', views.aprobar_peticion_persona, name='aprobar_peticion_persona'),
    path('aprobar_personas/masivo/', views.aprobar_masivo_personas, name='aprobar_masivo_personas'),
    #COCA ORGANIZACIÓN
    path('coca/org', views.peticion_organizacion, name='peticion_organizacion'),    
    path('coca/org/mod/org/<int:organizacion_id>', views.peticion_organizacion, name='mod_peticion_organizacion'),
    path('coca/org/ver/<str:token>', views.ver_peticion_organizacion, name='ver_peticion_organizacion'),  
    path('coca/org/cargar/responsable/<int:organizacion_id>', views.cargar_responsable_org, name='cargar_responsable_org'),
    path('coca/org/mod/responsable/<int:organizacion_id>/<int:responsable_id>', views.cargar_responsable_org, name='mod_responsable_org'),
    path('coca/org/cargar/afiliado/<int:organizacion_id>/', views.cargar_afiliado_org, name='cargar_afiliado_org'),
    path('coca/org/mod/afiliado/<int:organizacion_id>/<int:afiliado_id>', views.cargar_afiliado_org, name='mod_afiliado_org'),
    path('coca/org/del/responsable/<int:organizacion_id>/<int:responsable_id>', views.quitar_responsable_org, name='quitar_responsable_org'),
    path('coca/org/del/afiliado/<int:organizacion_id>/<int:afiliado_id>', views.quitar_afiliado_org, name='quitar_afiliado_org'),
    path('coca/org/finalizar/<int:organizacion_id>', views.finalizar_peticion_org, name='finalizar_peticion_org'),
    path('coca/org/mail/<int:organizacion_id>', views.peticion_org_enviar_email, name='peticion_org_enviar_email'),
    path('coca/org/del/org/<int:organizacion_id>', views.eliminar_peticion_org, name='eliminar_peticion_org'),
    path('coca/org/lista', views.lista_peticiones_org, name='lista_peticiones_org'),
    path('coca/org/lista/estado/<estado>', views.lista_peticiones_org, name='lista_peticiones_org'),
    path('coca/org/subir/doc/<str:token>', views.coca_subir_doc, name='coca_subir_doc'),
    path('coca/org/del/doc/<str:token>', views.coca_del_doc, name='coca_del_doc'),
    path('coca/org/aprobar_org/<int:organizacion_id>', views.aprobar_peticion_organizacion, name='aprobar_peticion_organizacion'),
    path('coca/personas/descargas/peticiones', views.download_peticiones_coca_personal, name='download_peticiones_coca_personal'),
    #Activacion:
    path('act/<int:inscripcion_id>/<int:num_doc>', views.activar_inscripcion, name='activar_inscripcion'),
]

coe/inscripciones/templates/elegir_turno.html
{% extends 'base_inscripciones.html' %}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 offset-lg-2">
                        <h2>Bienvenido {{inscripto.individuo}}</h2>
                        <p>Selecciona el turno que prefieras para {{ubicacion}}</p>
                        <br>
                        <div class="row">
                            {% for turno in turnos %}
                                <div class="col-sm-2 turnito">
                                    <p>Dia: {{turno.0|date:"l"}} ({{turno.0}})</p>
                                    <p>Horario: {{turno.1}}</p>
                                    <p>{{turno.2}} Disponibles</p>
                                    <a href="{% url 'inscripciones:turno_seleccionado' ubicacion_id=ubicacion.id inscripto_id=inscripto.id fecha=turno.0 hora=turno.1 %}">Pedir Turno</a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

coe/inscripciones/templates/lista_inscripciones.html
{% extends 'base_inscripciones.html' %}
{% load static %}
{% block content %}
    <div class="beneficiario container">
        <div class="row">
            <h2>Listado de Inscriptos</h2>
        </div>
        <div class="row">
        <div class="col-md-12">
            <table class="listado" id="table">
                <thead>
                    <tr>
                        <th>Profesion</th>
                        <th>Apellido</th>
                        <th>Nombre</th>
                        <th>Localidad</th>
                        <th>Telefono</th>
                        <th>Email</th>
                        <th>Fecha Inscripcion</th>
                        <th>Ver Detalle</th>
                    </tr>
                </thead>
                <tbody>
                    {% for inscripto in inscriptos %}
                        <tr>
                            <td>{{inscripto.get_profesion_display}}{{inscripto.oficio}}</td>
                            <td>{{inscripto.individuo.apellidos}}</td>
                            <td>{{inscripto.individuo.nombres}}</td>
                            <td>{{inscripto.individuo.domicilio_actual.localidad}}</td>
                            <td>{{inscripto.individuo.telefono}}</td>
                            <td>{{inscripto.individuo.email}}</td>
                            <td>{{inscripto.fecha}}</td>
                            <td><a href="{% url 'inscripciones:ver_inscripto' inscripto_id=inscripto.id %}">Ver Resumen</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

coe/inscripciones/templates/lista_inscripciones_social.html
{% extends 'base_inscripciones.html' %}
{% load static %}
{% block content %}
    <div class="beneficiario container">
        <div class="row">
            <h2>Listado de Voluntarios Sociales</h2>
        </div>
        <div class="row">
        <div class="col-md-12">
            <table class="listado" id="table">
                <thead>
                    <tr>
                        <th>Numero de Documento</th>
                        <th>Apellido</th>
                        <th>Nombre</th>
                        <th>Oficio</th>
                        <th>Domicilio</th>
                        <th>Localidad</th>
                        <th>Telefono</th>
                        <th>Email</th>
                        <th>Fecha Inscripcion</th>
                        <th>Estado</th>
                        <th>Ver Detalle</th>
                    </tr>
                </thead>
                <tbody>
                    {% for inscripto in inscriptos %}
                        <tr>
                            <td>{{inscripto.individuo.num_doc}}</td>
                            <td>{{inscripto.individuo.apellidos}}</td>
                            <td>{{inscripto.individuo.nombres}}</td>
                            <td>{{inscripto.oficio}}</td>
                            {% with inscripto.individuo.domicilio_actual as dom %}
                                <td>{{dom.calle}} {{dom.numero}}, {{dom.aclaracion}}</td>
                                <td>{{dom.localidad.nombre}}</td>
                            {% endwith %}
                            <td>{{inscripto.individuo.telefono}}</td>
                            <td>{{inscripto.individuo.email}}</td>
                            <td>{{inscripto.fecha}}</td>
                            <td>
                                <b>{{inscripto.get_estado_display}}</b>
                                {% if inscripto.tarea_asignada %}
                                    <br>
                                    {{inscripto.tarea_asignada}}
                                {% endif %}
                            </td>
                            <td><a href="{% url 'inscripciones:ver_inscripto' inscripcion_id=inscripto.id num_doc=inscripto.individuo.num_doc %}">Ver Resumen</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

coe/inscripciones/templates/menu_inscripciones.html
{% extends 'base_inscripciones.html' %}

{% load seguridad_tags%}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Menu Inscripciones:</h1>
                    <div class="col-md-8">
                        <ul class="menu_botones">
                            <li><a href="{% url 'inscripciones:lista_voluntarios' tipo_inscripto='PS'  %}">Ver Listado de Voluntarios de Salud</a></li>
                            <li><a href="{% url 'inscripciones:lista_voluntarios' tipo_inscripto='VS'  %}">Ver Listado de Voluntarios Sociales</a></li>
                            <li><a href="{% url 'inscripciones:lista_proyectos' %}">Ver Listado de Proyectos Estudiantiles</a></li>
                            
                            <hr>
                            <h3>Inscripciones Publicas</h3>
                            <li><a href="{% url 'inscripciones:inscripcion_salud'  %}">Inscripcion Voluntario de Salud</a></li>
                            <li><a href="{% url 'inscripciones:inscripcion_social'  %}">Inscripcion Voluntario Social</a></li>
                            <li><a href="{% url 'inscripciones:inscripcion_proyecto'  %}">Inscripcion Proyecto Estudiantil</a></li>
                            <li><a href="{% url 'inscripciones:pedir_coca'  %}">Peticion de COCA</a></li>
                            <hr>

                            <h3>Petición de COCA</h3>
                            <li><a href="{% url 'inscripciones:lista_peticiones_personales' estado='E'  %}">Peticiones Personales Esperando Aprobacion</a></li>
                            <li><a href="{% url 'inscripciones:lista_peticiones_personales' %}">Listado de Peticiones Personales</a></li>
                            <li><a href="{% url 'inscripciones:download_peticiones_coca_personal' %}">Descargar Listado de Peticiones Personales</a></li>
                            {% if request.user.is_superuser %}
                                <li><a href="{% url 'inscripciones:aprobar_masivo_personas' %}">Aprobar Personas Masivamente</a></li>
                            {% endif %}
                            <br>
                            <li><a href="{% url 'inscripciones:lista_peticiones_org' estado='E' %}">Peticiones de Organizaciones Esperando Aprobacion</a></li>
                            <li><a href="{% url 'inscripciones:lista_peticiones_org' %}">Listado de Peticiones de Organizaciones</a></li>
                            {% if request.user.is_superuser %}
                                <hr> 
                                <li><a href="{% url 'admin:index' %}">Administrador</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-md-4">
                        {% include 'info_user.html' %}
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

coe/inscripciones/templates/panel_peticion_org.html
{% extends 'base_informacion.html' %}

{% load static %}
{% load files_tags %}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <h2><b>Panel de Provisión de COCA - Organizaciones</b></h2>
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-6">
                                <h3 style="color:{% if organizacion.estado == 'C' %}red{% elif organizacion.estado == 'E' %}orange{% elif organizacion.estado == 'A' %}green{% else %}black{% endif %};"><b>Estado</b> {{organizacion.get_estado_display}}</h3>
                                <p><b>Denominación:</b> {{organizacion.denominacion}}</p>
                                <p><b>CUIT:</b> {{organizacion.cuit}}</p>
                                <p><b>Tipo de Organización:</b> {{organizacion.get_tipo_organizacion_display}}</p>
                                <p><b>Cantidad de Afiliados:</b> {{organizacion.cantidad}} (Cargados: {{organizacion.responsables.count}}r + {{organizacion.afiliados.count}}a)</p>
                                <p><b>E-mail de Contacto:</b> {{organizacion.mail_institucional}}</p>
                                <p><b>Localidad:</b> {{domicilio.localidad.nombre}}</p>
                                <p><b>Documentación Respaldatoria de la Organización:</b>
                                {% if organizacion.archivo_adjunto %}
                                    <a href="{{organizacion.archivo_adjunto.url}}">Ver Documento</a>
                                    <a href="{% url 'inscripciones:coca_del_doc' token=organizacion.token %}">
                                        <img class="icons" src="{% static '/img/icons/delete.png' %}">
                                    </a>
                                    <br>
                                    <a href="{% url 'inscripciones:coca_subir_doc' token=organizacion.token %}" style="font-weight:bold;color:red;">(Cambiar Archivo)</a>
                                {% else %}
                                    <a href="{% url 'inscripciones:coca_subir_doc' token=organizacion.token %}">CARGAR DOCUMENTACIÓN RESPALDATORIA</a><br>
                                    <i> NO SE OLVIDE DE SUBIR DOCUMENTACIÓN. </i>
                                {% endif %}
                            </div>
                            <div class="col-md-6">
                                <div class="bordeado importante">
                                    {% if organizacion.estado == 'C' %}
                                        <h3>Una vez que termine el ingreso de <b>TODA</b> la infomacion requerida, presione el botón de <b> FINALIZAR PROCESO</b>.</h3>
                                        <p>Su PEDIDO será ELIMINADO en {{limite}} horas, si es que no lo finaliza.</p>
                                        <br>
                                        <p>Hasta que el estado del pedido de COCA no se encuentre en <b>Pedido Cargado</b> nuestros operadores no lo analizarán.</p>                                   
                                    {% elif organizacion.estado == 'E' %}
                                        <h3>Nuestros Operadores estan analizando su requerimiento</h3>
                                        <br>
                                        <p>En caso de aprobarlo, le enviaremos un correo electronico a la cuenta informada para que descargue su autorizacion.</p>
                                    {% elif organizacion.estado == 'A' %}
                                        <h3>Su pedido fue aprobado</h3>
                                        <br>
                                        <p>Aquí tiene el comprobante de su aprobación. Puede descargarlo aquí.</p>
                                    {% endif %}
                                    {% if organizacion.estado != 'B' or organizacion.estado != 'A' %}
                                        <h3> IMPORTANTE: </h3>
                                        <br>
                                        <p> PARA PODER APROBAR SU PEDIDO, NECESITAMOS QUE USTED SUBA LA DOCUMENTACIÓN RESPALDATORIA.</p>
                                    {% endif %}

                                </div>
                            </div>
                        </div>
                        <hr>                        
                    </div>
                    <div class="col-md-4">
                        <ul class="menu_botones">
                            {% if organizacion.estado == 'C' %}
                                <li><a href="{% url 'inscripciones:mod_peticion_organizacion' organizacion_id=organizacion.id %}">Modificar Datos Basicos</a></li>                                                   
                                <li><a href="{% url 'inscripciones:cargar_responsable_org' organizacion_id=organizacion.id %}">Agregar Responsable Instituciónal</a></li>
                                <li><a href="{% url 'inscripciones:cargar_afiliado_org' organizacion_id=organizacion.id %}">Agregar Afiliados</a></li>
                                <li><a href="{% url 'inscripciones:finalizar_peticion_org' organizacion_id=organizacion.id %}">Finalizar Proceso</a></li>
                            {% endif %}                                                      
                            {% if perms.operadores.menu_inscripciones %}
                                <hr>
                                <p><b>Operadores</b></p>
                                {% if organizacion.estado == 'E'%}                                 
                                    <li><a href="{% url 'inscripciones:aprobar_peticion_organizacion' organizacion_id=organizacion.id %}">Aprobar Petición</a></li>
                                {% endif %} 
                                <li><a href="{% url 'inscripciones:peticion_org_enviar_email' organizacion_id=organizacion.id %}">Enviar Correo Electronico</a></li>
                                <li><a href="{% url 'inscripciones:eliminar_peticion_org' organizacion_id=organizacion.id %}">Eliminar PETICION</a></li>
                                <li><a href="{% url 'inscripciones:lista_peticiones_org' %}">Volver al Listado de Ingresos</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>                
                    
                <div class="row"></div>
                <hr>
                <h3><b>USTED DEBE CARGAR A LOS AFILIADOS DE LA ORGANIZACIÓN</b></h3>
                <table class="listado" id="table">
                    <thead>
                        <tr>
                            <th>Numero Documento</th>
                            <th>Nombre y Apellido</th>
                            <th>Fecha de Nacimiento</th>
                            <th>Correo Electronico</th>                                
                            <th>CUIL</th>                    
                            <th>Acciones</th>
                        </tr>
                    </thead>                          
                                
                    <tbody>
                    {% for afiliado in organizacion.afiliados.all %}
                        <tr>
                            <td>{{afiliado.individuo.num_doc}}</td>
                            <td>{{afiliado.individuo.apellidos}}, {{afiliado.individuo.nombres}}</td>
                            <td>{{afiliado.individuo.fecha_nacimiento}}</td>
                            <td>{{afiliado.individuo.email}}</td>
                            <td>{{afiliado.individuo.cuil}}</td>                           
                            <td>
                                <a href="{% url 'inscripciones:mod_afiliado_org' organizacion_id=organizacion.id afiliado_id=afiliado.id %}" target="_blank">
                                    <img class="icons" src="{% static 'img/icons/change.png' %}">
                                </a>
                                <a href="{% url 'inscripciones:quitar_afiliado_org' organizacion_id=organizacion.id afiliado_id=afiliado.id %}" target="_blank">
                                    <img class="icons" src="{% static '/img/icons/delete.png' %}">
                                </a>
                            </td>                                    
                        </tr>      
                    {% endfor %}
                    </tbody>
                </table>
                <div class="row"></div>
                <hr>
                <h3><b>USTED DEBE CARGAR AL RESPONSABLE DE LAS INSTITUCIÓN</b></h3>
                <table class="listado" id="table-r">
                    <thead>
                        <tr>
                            <th>Numero Documento</th>
                            <th>Nombre y Apellido</th>
                            <th>Rol</th>
                            <th>Correo Electronico</th>
                            <th>Telefono</th>                              
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for responsable in organizacion.responsables.all %}
                            <tr>
                                <td>{{responsable.individuo.num_doc}}</td>
                                <td>{{responsable.individuo.apellidos}}, {{responsable.individuo.nombres}}</td>
                                <td>{{responsable.rol}}</td>
                                <td>{{responsable.individuo.email}}</td>
                                <td>{{responsable.individuo.telefono}}</td>                              
                                <td>
                                    <a href="{% url 'inscripciones:mod_responsable_org' organizacion_id=organizacion.id responsable_id=responsable.id %}" target="_blank">
                                        <img class="icons" src="{% static 'img/icons/change.png' %}">
                                    </a>
                                    <a href="{% url 'inscripciones:quitar_responsable_org' organizacion_id=organizacion.id responsable_id=responsable.id %}" target="_blank">
                                        <img class="icons" src="{% static '/img/icons/delete.png' %}">
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>                                             
                {% if organizacion.emails_organizaciones.exists %}
                    <div class="row">
                        <h3>Emails Enviados al Responsable</h3>
                            <table class="listado">
                                <tr>
                                    <th>Fecha</th>
                                    <th>Asunto</th>
                                    <th>Cuerpo</th>
                                    <th>Operador</th>
                                </tr>
                                {% for email in organizacion.emails_organizaciones.all %}
                                    <tr>
                                        <td>{{email.fecha}}</th>
                                        <td>{{email.asunto}}</th>
                                        <td>{{email.cuerpo}}</td>
                                        <td>{{email.operador}}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    {% endif %}
                </div>
            </div>
        </section>
    </section>
{% endblock %}